# Generated by Django 4.1.4 on 2023-01-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("foto", models.ImageField(upload_to="images")),
                ("descricao", models.TextField()),
                ("email", models.CharField(max_length=50)),
            ],
        ),
    ]
