# Generated by Django 4.1.4 on 2023-01-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="CAMBIO",
            field=models.CharField(
                choices=[("Manual", "Manual"), ("Automatico", "Automatico")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="carro",
            name="data",
            field=models.DateField(),
        ),
    ]
