# Generated by Django 4.1.4 on 2023-01-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carros", "0002_alter_carro_cambio_alter_carro_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carro",
            old_name="CAMBIO",
            new_name="cambio",
        ),
    ]
